FROM node:10.15.3-alpine as build-deps

WORKDIR /usr/src/app
RUN npm install react-scripts@2.1.8 -g --silent

COPY ./src/package.json ./src/yarn.lock ./

RUN yarn
COPY ./src/ ./
RUN yarn build

FROM nginx:1.15.9-alpine
ARG ENVIRONMENT=local
ENV ENVIRONMENT="${ENVIRONMENT}"
COPY ./lib/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./lib/launch.sh ./
RUN chmod +x launch.sh
COPY config/client-side /usr/share/nginx/config/
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ./launch.sh